# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/main/pkg/config/v1alpha5/schema.json
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: uds-test-cluster
agents: 2
subnet: "172.28.0.0/16"
hostAliases:
  - ip: 172.28.0.4
    hostnames:
      - keycloak.bigbang.dev
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
volumes:
  - volume: /etc/machine-id:/etc/machine-id
    nodeFilters:
      - server:0
      - agent:*