apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: authservice-extension-provider
  namespace: istio-system
spec:
  hub: registry1.dso.mil/ironbank/tetrate/istio
  tag: 1.17.2-tetratefips-v0
  profile: empty
  components:
    pilot:
      enabled: true
  meshConfig:
    extensionProviders:
      - name: "authservice"
        envoyExtAuthzGrpc:
          service: "authservice.authservice.svc.cluster.local"
          port: "10003"
