application:
  name: authservice
  createNamespace: ###ZARF_VAR_AUTHSERVICE_CREATE_NAMESPACE###
  namespace: authservice
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/authservice.git
  ref:
    # renovate: datasource=gitlab-tags depName=big-bang/product/packages/authservice versioning=loose registryUrl=https://repo1.dso.mil
    tag: 0.5.3-bb.11
  values: |
    ###ZARF_VAR_AUTHSERVICE_VALUES###
  dependsOn:
    ###ZARF_VAR_AUTHSERVICE_DEPENDS_ON###
